dist: xenial

language: python

python:
    - "3.6"
    - "3.7"
    - "3.8"

sudo: false

matrix:
    fast_finish: true

install:
    pip install tox-travis

script:
    - tox

notifications:
    email: false
